spring:
  application:
    name: interview-platform

  datasource:
    url: jdbc:postgresql://localhost:5434/interview_platform?options=-c%20TimeZone=Asia/Kolkata
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379


    kafka:
      bootstrap-servers: localhost:9092
      producer:
        acks: all
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        properties:
          enable.idempotence: true
          linger.ms: 5
          max.block.ms: 2000

      consumer:
        group-id: session-event-persister
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret: ${JWT_SECRET:This is secret key}
  expiration-ms: 86400000